### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/language-maxscript#1]
## Task checklist
- [x] Fix inability to escape quote marks within strings _(done in 8e881d2)_
- [x] Outdent closing bracket of function definition when added to a new line _(done in d75400d3)_
- [x] Add rules for automatically indenting when hitting `enter` after typing some certain words _(done in d75400d3)_
- [x] Check MAXScript verbatim strings and de/referencing operators _(done in 8e881d2)_
- [x] ~~Add pattern-matching for `on <handler>` clauses and the like~~ _(not doing: not really needed)_
- [x] Add grammar rules for [MAXScript `time` values](http://help.autodesk.com/view/3DSMAX/2016/ENU/?guid=__files_GUID_46ECBAD7_35E9_43BD_8A8C_849772924805_htm#CODEBLOCK_1270404DAB0247EBB307CCF5C1A4C804) _(done in 8e881d2)_
